"""empty message

Revision ID: b9b0d496f145
Revises: 3cf8a988abbf
Create Date: 2025-02-07 04:40:28.124427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b0d496f145'
down_revision = '3cf8a988abbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_fav_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_people_people_fav_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_fav_id'], ['id'])
        batch_op.drop_column('people_fav_name')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_fav_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planets_planet_fav_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planet_fav_id'], ['id'])
        batch_op.drop_column('planet_fav_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_fav_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_planet_fav_name_fkey', 'planets', ['planet_fav_name'], ['planet_name'])
        batch_op.drop_column('planet_fav_id')

    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_fav_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_people_fav_name_fkey', 'people', ['people_fav_name'], ['name'])
        batch_op.drop_column('people_fav_id')

    # ### end Alembic commands ###
